service: movie-theather-api
frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.8

functions:
  getReservations:
    handler: controllers/reservation_controller.get_reservations
    events:
      - http:
          path: /reservation
          method: get

  deleteReservation:
    handler: controllers/reservation_controller.delete_reservation
    events: 
      - http:
          path: /reservation
          method: delete

plugins:
  - serverless-offline
  - serverless-python-requirements

